google/citest

- citest/json_contract/contract.py
- citest/json_contract/observation_failure.py
- citest/json_contract/observation_verifier.py
- citest/json_contract/observer.py
- citest/json_contract/value_observation_verifier.py
- tests/json_contract/contract_test.py
- tests/json_contract/observation_failure_test.py
- tests/json_contract/observation_verifier_test.py
- tests/json_contract/observer_test.py
- tests/json_contract/value_observation_verifier_test.py
@lwander This is step 3, updating the contract and observers to be aware of the changes to the predicates. The main change here is that the verifier is now more based on PathPredicate than MapPredicate. Even so, since the results are only used for reporting and are self describing, there isnt further down-stream impact
> Refactored observers, verifiers, and contracts.

- spinnaker/spinnaker_system/google_kato_test.py
Added retry to observer in google kato deregister lb test. Combats test flakiness due to timing.
> Added retry to observer in google kato deregister lb test.

- README.md
- citest/aws_testing/aws_contract.py
- citest/gcp_testing/gce_contract.py
- citest/json_predicate/__init__.py
- citest/reporting/html_index_renderer.py
- citest/service_testing/http_observer.py
- spinnaker/spinnaker_system/aws_kato_test.py
- spinnaker/spinnaker_system/aws_smoke_test.py
- spinnaker/spinnaker_system/google_kato_test.py
- spinnaker/spinnaker_system/google_server_group_test.py
- spinnaker/spinnaker_system/google_smoke_test.py
@lwander This is the final refactoring step, mostly updating the package name in the consumers. Since most high level usage is at the contract level, not much is affected.
There is a subtle problem here. The observers want to expand out lists but sometimes contracts are written against the list as a whole (contains an element that...). This is easily fixed by specifying the DONT_ENUMERATE_TERMINAL path, however it is a subtle issue that is going to grow into an annoyance. I'll need to address this, but have higher priority concerns in other projects so need to come back to it later.
> Updated remaining modules affected by refactoring to complete it.

- citest/gcp_testing/gce_util.py
Fix to handle HTTPErrors as success for tunneling. @ewiseblatt PTAL.
> Fix to handle HTTPErrors as success for tunneling.

- citest/service_testing/__init__.py
- citest/service_testing/http_observer.py
@lwander 
The "_error_comment_or_none" in the base class interface is hacky but I'd like to wait until later to clean it up. This is an enabling CL to add some new spinnaker tests in another CL.
> Added HttpObservationFailureVerifier

- citest/gcp_testing/gce_util.py
@lwander @jtk54 PTAL
@ewiseblatt FYI - A recent change to Gate put a redirect on / to Deck, which citest does not bring up.
> Make test check against /health instead of /

- spinnaker/spinnaker_system/kube_smoke_test.py
@ewiseblatt 
Addresses TODO since load balancers (services) are functional for the Kubernetes Spinnaker integration.
> Associate service with RC in kube_smoke_test

- spinnaker/spinnaker_system/bake_and_deploy_test.py
Make sure tests don't run in bake+deploy test if the proper flags are set/not set. @lwander PTAL. @ewiseblatt FYI.
> Make sure tests don't run in bake+deploy test.

- spinnaker/spinnaker_system/google_quota_test.py
Added service account to quota tests commands. They used to depend on the active gcloud service account, this PR makes them much more robust. @lwander @danielpeach PTAL. @ewiseblatt FYI.
> Added service account to quota tests commands.

- citest/base/journal_logger.py
- citest/service_testing/agent_test_case.py
- tests/service_testing/agent_test_case_test.py
- tests/service_testing/base_agent_test.py
- tests/service_testing/fake_agent.py
Dependency was only for storing objects in the journal.
Since it is already using JournalLogger, and store only forwards to the
global runner's logger, it asks the JournalLogger to store the object instead.
Also added test for AgentTestCase.
@jtk54
> Remove AgentTestCase's dependency on TestRunner.

- citest/aws_testing/aws_contract.py
- citest/base/execution_context.py
- citest/gcp_testing/gcp_compute_agent.py
- citest/gcp_testing/gcp_contract.py
- citest/gcp_testing/quota_predicate.py
- citest/json_contract/observer.py
- citest/json_contract/value_observation_verifier.py
- citest/json_predicate/__init__.py
- citest/json_predicate/binary_predicate.py
- citest/json_predicate/cardinality_predicate.py
- citest/json_predicate/logic_predicate.py
- citest/json_predicate/map_predicate.py
- citest/json_predicate/path_predicate.py
- citest/json_predicate/path_result.py
- citest/json_predicate/path_transforms.py
- citest/json_predicate/predicate.py
- citest/kube_testing/kube_contract.py
- spinnaker/spinnaker_system/google_kato_test.py
- tests/gcp_testing/quota_predicate_test.py
- tests/json_contract/observation_verifier_test.py
- tests/json_contract/observer_test.py
- tests/json_contract/value_observation_verifier_test.py
- tests/json_predicate/binary_predicate_test.py
- tests/json_predicate/cardinality_predicate_test.py
- tests/json_predicate/logic_predicate_test.py
- tests/json_predicate/map_predicate_test.py
- tests/json_predicate/path_predicate_helpers_test.py
- tests/json_predicate/path_predicate_result_test.py
- tests/json_predicate/path_predicate_test.py
- tests/json_predicate/path_transforms_test.py
Renamed CloneableInContext to CloneableWithNewSource to avoid
overloading the term "context". The context in journals and evaluation
are still overloaded but expect them to become explicitly related in
the future.
@lwander this is the last of the CLs for now. This completes the feature for runtime value injection from an execution context.
> Added context to predicate evaluation

- spinnaker/spinnaker_system/kube_smoke_test.py
Replication controllers have been replaced with replica sets for the Kubernetes provider. This caused the tests to fail.
@ewiseblatt
> Replace RC with RS in kube_smoke_test

- citest/json_contract/contract.py
- spinnaker/spinnaker_system/google_kato_test.py
@jtk54 
TBR
I dont think this is it because the test passes for me in < 2 secs over all so there was plenty of time before. But this will help rule out time being a factor in the failures we've been seeing.
Also slow down the poll rate for short observations.
> Give more time to kato deregister test

- citest/base/execution_context.py
- citest/service_testing/agent_test_case.py
- citest/service_testing/operation_contract.py
- spinnaker/spinnaker_system/bake_and_deploy_test.py
- tests/service_testing/agent_test_case_test.py
@jtk54 
The old status_collector (and cleanup) functions predated contexts.
Changed status_collector to status_extractor, whose responsibility can
be to move values from the status into the context. in the case of spinnaker,
this could traverse the complex json data to extract out a couple individual
fields that might be referenced by a test.
Cleanup just takes a context. The run_test_case method adds the verify results
into the context so they are still available (and the status was already there).
I also renamed the keys that the run_test_case writes into the context to be
camel case to match the type names. I dont think anything was referencing this
yet.
> Changed operation status_collector and cleanup functions.

- citest/service_testing/base_agent.py
- spinnaker/README.md
- spinnaker/spinnaker_system/aws_kato_test.py
- spinnaker/spinnaker_system/aws_smoke_test.py
- spinnaker/spinnaker_system/bake_and_deploy_test.py
- spinnaker/spinnaker_system/google_http_lb_upsert_scenario.py
- spinnaker/spinnaker_system/google_kato_test.py
- spinnaker/spinnaker_system/google_server_group_test.py
- spinnaker/spinnaker_system/google_smoke_test.py
- spinnaker/spinnaker_system/kube_smoke_test.py
- spinnaker/spinnaker_testing/gate.py
- spinnaker/spinnaker_testing/spinnaker_test_scenario.py
@jtk54 
This is a first PR preparing to migrate out the spinnaker tests. I
updated some docs and renamed some of the parameters and bindings to
be less daunting and clearer what the parameters are for.
The changes to binding dictionary keys is a breaking change. I'm not
aware of any significant inconvienience this will cause people
(e.g. PRs in progress) The breaking changes are straight forward:
<PLATFORM>_CREDENTIALS -> SPINNAKER_<PLATFORM>_ACCOUNT
The change in parameters is a deprecated change, maintaining support
for the old interface. I'll keep these around of a while since it is
easy to support.
> Breaking change to spinnaker.binding key names.

- spinnaker/spinnaker_system/google_http_lb_upsert_scenario.py
- spinnaker/spinnaker_system/google_http_lb_upsert_server_test.py
@lwander please review. These tests share a scenario, so they were performing illegal operations on components when run in parallel in the nightly builds.
> Resolved naming collisions between http upsert tests.

- spinnaker/spinnaker_system/google_http_lb_upsert_scenario.py
- spinnaker/spinnaker_system/google_http_lb_upsert_test.py
- spinnaker/spinnaker_system/google_smoke_test.py
Wires two simple Http LB cases into the Google smoke tests. @ewiseblatt please review.
> Http LB tests integrated into Google smoke tests.

- spinnaker/spinnaker_system/google_http_lb_upsert_scenario.py
@ewiseblatt please review. Creating a server group previously used the `securityGroups` field to specify security groups, but now only uses `tags`. I modified the operation descriptions for creating the security group and server group to use the tags. This should fix the previous test failure.
> L7 upsert test: Make 'add server group' use tags, not security group.

- citest/reporting/html_renderer.py
- citest/reporting/simplify_entity_transforms.py
@jtk54 
The data model dumps show the literal data model. There are some
common types that use lists for a general case so these are reported
out as lists even if the particular instance is only dealing with one
element.
If the list is just an implementation detail (as opposed to something
that is fundamentally a list and may contain one) then this list rendering
adds abstraction overhead and complexity for the reader. This PR allows
certain types to explicity transform the interpretation of their encodings
depending on the context of the instance value.
For example PathValueResult contains a list of values at a given path
because in general paths can pass through lists as intermediate nodes,
so have different branches down the path resulting in different values.
If there is no list, then …
> Added rendering transforms to simplify report structure

- citest/json_predicate/binary_predicate.py
- citest/json_predicate/map_predicate.py
- citest/json_predicate/path_predicate.py
- tests/json_predicate/binary_predicate_test.py
@jtk54 
I also changed PathPredicate to allow configuration of whether or not
to expand list terminals. It defaults to exapand but DICT_MATCh makes
it not. I think this makes it more natural to specify constraints on
attributes, and the feature could be used for PathPredicate cases.
> Refactored DICT_MATCH so that it allows multi-level path attributes.

- citest/reporting/generate_html_report.py
- citest/reporting/html_document_manager.py
- citest/reporting/html_index_renderer.py
- citest/reporting/html_renderer.py
- pylint.rc
- spinnaker/spinnaker_system/google_front50_test.py
- tests/reporting/html_renderer_test.py
@jtk54 
This is a refactoring of the HTML generation to use beautiful soup as you suggested earlier last week. Except it doesnt.
While it is cleaner, it took >10x longer to run. That's especially surprising because I'm not really parsing HTML -- I am generating it. So that means the overhead is likely in building and managing the data model. To process the http load balancer test journal went from 12s to over 2m. That's extremely significant and a turn off from wanting to do this.
Another interesting stat is that I turned off formatting which causes the size to drop from 173M to 44M yet the time to write it out increases from around 1s to 33s. The BS write is doing to conversion from its data model into HTML which is why it takes so long, yet even so it is almost 3x as long as my original …
> Refactored HTML rendering to use BeautifulSoup API

- citest/gcp_testing/gcp_agent.py
@ttomsu 
This works around the problem you were seeing last week.
I dont like it, but dont see a way to force every different script to update.
> Suppress warning from google apiclient.

- citest/base/global_journal.py
- citest/gcp_testing/gce_util.py
- citest/gcp_testing/gcloud_agent.py
In python 3.7 and later, ["async" is a reserved word](https://docs.python.org/3/whatsnew/3.7.html). This change renames a variable with that name to avoid syntax errors when running with these later versions of Python.
Also adds a check re: the presence of the [`os.fchmod`](https://docs.python.org/3/library/os.html#os.fchmod) attribute to avoid errors when running on Windows.
> fix(python3): remove async reserved word
