google/citest

spinnaker/spinnaker_system/google_kato_test.py

Moved deregister lb observer retry to clause creation.

Moved deregister lb retry to clause creation.

---

citest/json_predicate/path_predicate_result.py

Tweaked some snapshot details.

---

citest/json_predicate/json_error.py
citest/kube_testing/__init__.py
citest/kube_testing/kube_contract.py
citest/kube_testing/kubectl_agent.py
spinnaker/spinnaker_system/kube_smoke_test.py
spinnaker/spinnaker_testing/spinnaker_test_scenario.py

This replaces the earlier branch because, for some reason, it doesnt think it is mergable. I hope this is.
It is [should be] exactly the same but is recreated from a new branch off master using a diff against it.
@lwander

Initial smoke test for Kubernetes.

---

spinnaker/spinnaker_system/aws_smoke_test.py
spinnaker/spinnaker_system/bake_and_deploy_test.py
spinnaker/spinnaker_system/google_smoke_test.py

Replace --test_component_name argument with internlal __lb_name

---

citest/base/test_runner.py
citest/reporting/generate_html_report.py

Always generate HTML output in test runner for ease of use for now.

---

citest/json_contract/contract.py
citest/service_testing/agent_test_case.py
citest/service_testing/base_agent.py
citest/service_testing/cli_agent.py
citest/service_testing/http_agent.py
spinnaker/spinnaker_testing/jenkins_agent.py
tests/service_testing/base_agent_test.py

@ttomsu This change would have let you change the per-operation timeout yesterday

Expose max_wait_secs per operation (and make it a float)

---

README.md
overview.md

@lwander 
@rbuskens, you might find this helpful.

Updated docs.

---

spinnaker/spinnaker_testing/expression_dict.py
spinnaker/spinnaker_testing/gate.py

Fixed spring regexp to handle empty default.

---

citest/gcp_testing/gcloud_agent.py
citest/kube_testing/kube_contract.py
citest/service_testing/agent_test_case.py

Small typo fixes

---

citest/service_testing/http_agent.py
spinnaker/spinnaker_testing/spinnaker_test_scenario.py

@lwander 
This also removes out a non-standard use of trace parameter that was causing a lint error. Eventually I will remove all trace of "trace".

Added HTTP put support.

---

README.md
overview.md

Enable syntax highlighting in README & overview

---

citest/gcp_testing/__init__.py
citest/gcp_testing/gcs_contract.py
citest/gcp_testing/gsutil_agent.py

Added GoogleCloudStorage agent

---

spinnaker/spinnaker_system/google_front50_test.py
spinnaker/spinnaker_testing/front50.py

@lwander 
This currently tests only Application objects. The critical integration is the same for all the different objects, so I think this is sufficient as a smoke test for the time being.

Test Front50 use of Google Cloud Storage

---

spinnaker/spinnaker_system/kube_smoke_test.py

@ewiseblatt 
I'm going to enable this test in the nightly builds next.

Fix MIG/RC terminology usage

---

citest/gcp_testing/google_session.py

Added GoogleSession logout. @ewiseblatt FYI.

Added GoogleSession logout.

---

citest/gcp_testing/google_session.py

Handle session logouts gracefully. @ewiseblatt PTAL. @ttomsu FYI.

Handle session logouts gracefully.

---

citest/service_testing/agent_test_case.py
citest/service_testing/operation_contract.py
spinnaker/spinnaker_system/bake_and_deploy_test.py
spinnaker/spinnaker_testing/jenkins_agent.py
spinnaker/spinnaker_testing/spinnaker.py
spinnaker/spinnaker_testing/spinnaker_test_scenario.py

Adds mechanism to cleanup from tests.
Some lint fixes.
@lwander

Delete image created as side effect to the bake and deploy test.

---

citest/gcp_testing/__init__.py
citest/gcp_testing/gcp_api.py
citest/service_testing/http_observer.py
spinnaker/spinnaker_system/google_front50_test.py

Better support for expecting errors from GCP APIs

---

spinnaker/spinnaker_testing/spinnaker.py
spinnaker/spinnaker_testing/spinnaker_test_scenario.py

@lwander github doesnt show the big block as being an indentation change as well. I just added the except: blocks

Log exceptions

---

citest/base/test_runner.py
citest/service_testing/agent_test_case.py

Added hook to base runner to initialize argument parser (so can inject
scenario specific arguments) and provided a means for the TestRunner to
store shared data across TestCase instances. This still isnt ideal, but
is a simple change that will remove part of the messy coupling and
simplify bootstrap.
@lwander or @jtk54

Enable decoupling of AgentTestScenario and AgentTestCase.

---

spinnaker/spinnaker_system/google_front50_test.py

Allow some time for files to show up.

---

spinnaker/spinnaker_system/bake_and_deploy_test.py

Fixed typo

---

citest/base/journal.py
citest/json_contract/value_observation_verifier.py
citest/reporting/html_renderer.py
tests/json_contract/value_observation_verifier_test.py

Fixed reporting

---

spinnaker/spinnaker_system/kube_smoke_test.py

Give kubernetes more time

---

citest/gcp_testing/gcp_error_predicates.py
citest/gcp_testing/quota_predicate.py
citest/json_contract/contract.py
citest/json_contract/observation_verifier.py
citest/json_contract/value_observation_verifier.py
citest/json_predicate/binary_predicate.py
citest/json_predicate/cardinality_predicate.py
citest/json_predicate/logic_predicate.py
citest/json_predicate/map_predicate.py
citest/json_predicate/path_predicate.py
citest/json_predicate/path_predicate_result.py
citest/json_predicate/path_result.py
citest/json_predicate/path_transforms.py
citest/json_predicate/predicate.py

Use kwargs in Predcate/Result initializers.

---

tests/gcp_testing/gcp_agent_test.py
tests/gcp_testing/gcp_contract_test.py
tests/gcp_testing/test_gcp_agent.py

refactored from gcp_agent_test and borrowed from gcloud_contract_test

Added gcp_contract test

---

citest/json_predicate/binary_predicate.py
tests/json_predicate/binary_predicate_test.py

Fixed checking and reporting failures in nested values

---

spinnaker/spinnaker_system/bake_and_deploy_test.py

Fixed call and most lint warnings in bake_and_deploy.

---

spinnaker/spinnaker_system/google_front50_test.py

Updated expectations for front50 change.

---

spinnaker/spinnaker_system/google_kato_test.py

disabled google http load balancer tests

---

spinnaker/spinnaker_system/google_front50_test.py

Added pipeline test and test history.

---

spinnaker/spinnaker_system/google_front50_test.py

Added retry to operations that hit gcs because updates are not immediate

---

.gitignore
setup.py
spinnaker/spinnaker_system/google_http_lb_upsert_scenario.py
spinnaker/spinnaker_system/google_http_lb_upsert_server_test.py
spinnaker/spinnaker_system/google_http_lb_upsert_test.py

@ewiseblatt please review. @duftler FYI. This is a pretty comprehensive test on L7 load balancer upsert without associated server groups. I'll add another set of tests in the future that test the L7 server group operations and validates L7 upsert when there are server groups attached.

Added L7 LB upsert test.

---

spinnaker/spinnaker_system/google_front50_test.py

Fixed front50 retry params

---

citest/reporting/html_document_manager.py
citest/reporting/html_renderer.py

Fixed rendering <pre> as link anchors

---

spinnaker/spinnaker_system/google_http_lb_upsert_scenario.py

Wait longer for a server group to associate with an L7 LB.

---

spinnaker/spinnaker_system/google_front50_test.py

Added retries for front50 delete_pipeline test.

---

spinnaker/spinnaker_system/google_http_lb_upsert_scenario.py

@ewiseblatt This takes care of the recent L7 test failures.

Updated L7 upsert description for recent refactor.

---

citest/base/execution_context.py
citest/base/snapshot.py
citest/gcp_testing/gcp_agent.py

Tweaks for using application credentials and some error handling.

---

citest/gcp_testing/resource_snapshot.py

Tolerate HTTP errors.

---

citest/gcp_testing/resource_snapshot.py

I want this to avoid deleting "operations".
Also, dont bother listing things that cannot be deleted. They appear to be things like zones.
@lwander

Can exclude resources.

---

citest/gcp_testing/gce_util.py
citest/gcp_testing/resource_snapshot.py
citest/json_predicate/path_result.py
citest/reporting/generate_html_report.py
citest/reporting/html_document_manager.py
citest/reporting/html_index_renderer.py
citest/reporting/html_renderer.py
citest/service_testing/http_agent.py
tests/reporting/html_renderer_test.py

@jtk54 
Sorry to have to do this. It's basically adding a data structure and shuffling code around. The heuristics and stuff are the same. It lets me store what's different rather than just print it, even though in the end I just print it. The value here is that I can clean up the output.

Refactored displaying diff output.

---

citest/gcp_testing/__init__.py
citest/gcp_testing/gcp_appengine_agent.py

added app engine agent

---

.gitignore
README.md
citest/azure_testing/__init__.py
citest/azure_testing/az_agent.py
citest/azure_testing/az_contract.py

@ewiseblatt PTAL.  If good I can rebase and submit.  This is initial PR for citest Azure support

Initial commit of azure agent/contract

---

citest/aws_testing/aws_python_agent.py
citest/base/journal_logger.py
citest/gcp_testing/gcp_agent.py
tests/base/journal_logger_test.py

Encapsulate context logging

---

citest/aws_testing/aws_cli_agent.py
citest/aws_testing/aws_cli_contract.py
citest/aws_testing/aws_python_agent.py
citest/aws_testing/aws_python_contract.py
citest/azure_testing/az_agent.py
citest/azure_testing/az_contract.py
citest/base/base_test_case.py
citest/base/journal_logger.py
citest/gcp_testing/gce_util.py
citest/gcp_testing/gcloud_agent.py
citest/gcp_testing/gcloud_contract.py
citest/gcp_testing/gcp_agent.py
citest/gcp_testing/gcp_contract.py
citest/json_contract/observer.py
citest/kube_testing/kube_contract.py
citest/kube_testing/kubectl_agent.py
citest/openstack_testing/os_agent.py
citest/openstack_testing/os_contract.py
citest/service_testing/agent_test_case.py
citest/service_testing/base_agent.py
citest/service_testing/cli_agent.py
citest/service_testing/http_agent.py
citest/service_testing/http_observer.py
tests/gcp_testing/fake_gcloud_agent.py
tests/json_contract/contract_test.py
tests/service_testing/agent_test_case_test.py
tests/service_testing/fake_agent.py

Remove trace
